export enum SystemErrors {
  E400_VALIDATION_ERROR = 'E400_VALIDATION_ERROR',
  E400_UNIDENTIFIED_BAD_REQUEST = 'E400_UNIDENTIFIED_BAD_REQUEST',
  E401_UNAUTHORIZED = 'E401_UNAUTHORIZED',
  E403_FORBIDDEN = 'E403_FORBIDDEN',
  E404_UNIDENTIFIED_NOT_FOUND = 'E404_UNIDENTIFIED_NOT_FOUND',
  E409_UNIDENITIFIED_CONFLICT = 'E409_UNIDENITIFIED_CONFLICT',
  E500_UNIDENTIFIED_INTERNAL_SERVER_ERROR = 'E500_UNIDENTIFIED_INTERNAL_SERVER_ERROR',
}
